config/routes.rb
Rails.application.routes.draw do
  resources :item_requests

  get 'dashboard/index'

  get 'spage/welcome'

  get 'spage/about'

  get 'spage/contact'

  get 'spage/legal'

  get 'spage/privacy'

  get 'items/search'

  get 'items/rentnow'

  get 'acceptoffer/:id' => 'item_requests#acceptoffer'
  get 'rejectoffer/:id' => 'item_requests#rejectoffer'
  get 'userofferindex' =>'item_requests#offerindex'
  get 'userrequestindex' => 'item_requests#requestindex'
  get 'pendingrequestindex' => 'item_requests#pendingrequestindex'
  get 'acceptrequestindex' => 'item_requests#acceptrequestindex'
  get 'rejectrequestindex' => 'item_requests#rejectrequestindex'
  get 'pendingofferindex' => 'item_requests#pendingofferindex'
  get 'acceptofferindex' => 'item_requests#acceptofferindex'
  get 'rejectofferindex' => 'item_requests#rejectofferindex'
  get 'items/renthistory' => 'items#renthistory'

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }
  resources :items
  post 'reviews/create'
  root to: 'spage#welcome'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @myitems = Item.where(:user_id => current_user.id)
    user = current_user.id
    owneditems=Item.where(user_id: user).select('id')
    @myitem_requests=ItemRequest.where(:item_id =>owneditems.map(&:id),:status=>"Requested")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container" style="padding-top: 10px;">
  <div class="row">
    <div class="col-sm-12 col-md-12">
      <div class="well">
        <div class="well" style="float: left; border: 0px;">
          <% if current_user.avatar_url.present? %>
              <span style=""> <%= image_tag current_user.avatar_url.to_s, :size => "184x184", :class => "img-circle" %></span>
          <% else %>
              <img src="http://i0.wp.com/coverlandia.net/images/default_avatar.jpg" class="img-circle" width="184px">
          <% end %>
        </div>
        <div class="well" style="border: 0px;">
          <h1 style="text-align: left; margin-left: 15px;">Welcome <%= current_user.first_name %> <%= current_user.last_name %></h1>
          <h6 style="text-align: left; margin-left: 15px;">Email: <%= current_user.email %></h6>
          <h6 style="text-align: left; margin-left: 15px;">Phone: <%= current_user.phone %></h6>
          <h6 style="text-align: left; margin-left: 15px;">Address: <%= current_user.address %></h6>
          <h6 style="text-align: left; margin-left: 15px;">Signin count: <%= current_user.sign_in_count %></h6>
          <h6 style="text-align: left; margin-left: 15px;">A member since: <%= time_ago_in_words(current_user.created_at) %></h6>
        </div>
      </div>
    </div>

  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-3 col-md-3">
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Account</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body" style="padding:0px;">
              <table class="table" style="margin-bottom: 0px;">
                <tr>
                  <td>
                    <%= link_to('profile', edit_user_registration_path )%>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Items</a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body" style="padding:0px;">
              <table class="table" style="margin-bottom: 0px;">
                <tr>
                  <td>
                    <%= link_to('My items', items_path )%>  <span class="label label-success"><%= @myitems.count %></span>
                  </td>
                </tr>
                <tr>
                  <td>
                    <%= link_to('New item', new_item_path )%>
                  </td>
                </tr>

              </table>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">Offers</a>
              <% if @myitem_requests.count > 0 %>
                <span class="label label-success"><%= @myitem_requests.count %></span>
              <% end %>
            </h4>
          </div>
          <div id="collapseThree" class="panel-collapse collapse">
            <div class="panel-body" style="padding:0px;">
              <table class="table" style="margin-bottom: 0px;">
                <tr>
                  <td>
                    <%= link_to "All Offers", :controller=>:item_requests, :action => :offerindex %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <%= link_to "Pending Offers", :controller=>:item_requests, :action => :pendingofferindex %>
                    <span class="label label-success"><%= @myitem_requests.count %></span>
                  </td>
                </tr>
                <tr>
                  <td>
                    <%= link_to "All Requests", :controller=>:item_requests, :action => :requestindex %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <%= link_to "Pending Requests", :controller=>:item_requests, :action => :pendingrequestindex %>
                  </td>
                </tr>
                <tr>
                  <td>
                    <!--span class="glyphicon glyphicon-trash text-danger"></span><a href="" class="text-danger">
                    Delete offer</a-->
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">Rent</a>
            </h4>
          </div>
          <div id="collapseFour" class="panel-collapse collapse">
            <div class="panel-body" style="padding:0px;">
              <table class="table" style="margin-bottom: 0px;">
                <tr>
                  <td>
                    <a href="">Rented items</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="">return an item</a>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-9 col-md-9">
      <div class="well">
        <h1>
          Dashboard and Activities</h1>
        User Dashboard Accordion Menu



      </div>
    </div>
  </div>
</div>