config/routes.rb
Rails.application.routes.draw do
  resources :item_requests

  get 'dashboard/index'

  get 'spage/welcome'

  get 'spage/about'

  get 'spage/contact'

  get 'spage/legal'

  get 'spage/privacy'

  get 'items/search'

  get 'items/rentnow'

  get 'acceptoffer/:id' => 'item_requests#acceptoffer'
  get 'rejectoffer/:id' => 'item_requests#rejectoffer'
  get 'userofferindex' =>'item_requests#offerindex'
  get 'userrequestindex' => 'item_requests#requestindex'
  get 'pendingrequestindex' => 'item_requests#pendingrequestindex'
  get 'acceptrequestindex' => 'item_requests#acceptrequestindex'
  get 'rejectrequestindex' => 'item_requests#rejectrequestindex'
  get 'pendingofferindex' => 'item_requests#pendingofferindex'
  get 'acceptofferindex' => 'item_requests#acceptofferindex'
  get 'rejectofferindex' => 'item_requests#rejectofferindex'
  get 'items/renthistory' => 'items#renthistory'

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }
  resources :items
  post 'reviews/create'
  root to: 'spage#welcome'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :item_requests, dependent: :delete_all
  has_many :reviews, dependent: :delete_all

  validates :name, :description, :price, presence: true

  mount_uploader :image, ImageUploader

=begin
  scope :address, self.joins(User.select(:address))
  scope :latitude, self.joins(User.select(:latitude))
  scope :longitude, self.joins(User.select(:longitude))
=end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /items
  # GET /items.json
  def index
    #@items = Item.all
    @items = Item.where(:user_id => current_user.id)
    @items1 = Item.all
  end

  def index_user

  end

  def rentnow
   # @itemrent = Item.find(params[:item])
   #
   # @item_request = ItemRequest.new
   # @item_request.item_id = params[:item]
   # @item_request.user_id = @itemrent.user.id
   # @item_request.save
    session[:current_item_id] = params[:item]

    redirect_to(controller: "item_requests", action:"new")
  end

  def new_request

  end
  # GET /items/1
  # GET /items/1.json
  def show

  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  def renthistory
    item=params[:format]

    @item_requesthistory = ItemRequest.where('item_id==? AND status==? AND toDate>?',
                                       item, "Accepted", Date.today )
    @item_requestschedule = ItemRequest.where('item_id==? AND status==? AND fromDate<?',
                                       item, "Accepted", Date.today )
  end

  # POST /items
  # POST /items.json
  def create
    @categories = Category.all
     @item = Item.new(item_params)
   @item.user_id= current_user.id
    respond_to do |format|
      if @item.save
        @items = Item.where(:user_id => current_user.id)
        format.html { redirect_to @item,  notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    cu = User.find(current_user.id)
    @nu = User.near(cu.address, 50)
    @item = Item.where('user_id IN (?) AND user_id != ?',  @nu.each do |t| t.id end, current_user.id)
=begin
    @hash = Gmaps4rails.build_markers(User.where('id IN (?)', @item.each do |t| t.user_id end)) do |user, marker|
                                        marker.lat user.latitude
                                        marker.lng user.longitude
                                      end
=end
    if params[:search].present?
      @item = Item.where('name like ? AND user_id IN (?) AND user_id != ?', "%#{params[:search]}%", @nu.each do |t| t.id end, current_user.id)
      #@item = Item.all(:joins => :users, :select => "items.*, users.address as address, users.latitude as latitude, users.longitude as longitude", :group => "users.id")
      #all_items = @item

    else
      @item = Item.where('user_id IN (?) AND user_id != ?',  @nu.each do |t| t.id end, current_user.id)
      #@item = Item.joins(:user)
      #all_items = @item
    end


    #@tomark = User.where('id IN (?)', @nu.each do |t| t.id end)
    @hash = Gmaps4rails.build_markers(@item) do |i, marker|
      marker.lat i.user.latitude
      marker.lng i.user.longitude
      marker.infowindow i.name+i.description+"$"+i.price.to_s
      #marker.title  i.name
      #marker.sidebar "i'm the sidebar"
      marker.json({ :id => i.id, :foo => "bar" })
    end

    @hash += Gmaps4rails.build_markers(User.find(current_user.id)) do |i, marker|
      marker.lat i.latitude
      marker.lng i.longitude
      marker.infowindow i.first_name+" "+i.last_name+"<br/>"+i.address
      marker.picture({"url" => "/assets/hp.png", "width" =>  32, "height" => 44})
      #marker.picture({"url" => 'http://wiki.kerbalspaceprogram.com/w/images/thumb/1/14/Target_prograde.svg/32px-Target_prograde.svg.png', "width" =>  32, "height" => 32})
    end

=begin
    @tomark = User.where('id IN (?)', @nu.each do |t| t.id end)
    @hash = Gmaps4rails.build_markers(@tomark) do |user, marker|
        marker.lat user.latitude
        marker.lng user.longitude
      end
=end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :image, :price, :keywords, :category_id, :user_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="container" style="margin-bottom: 15px;">
  <%- model_class = Item -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>
</div>

app/views/items/index.html.erb
<div class="container" style="margin-bottom: 15px;">
  <%- model_class = Item -%>
  <div class="page-header">
    <h1>Your <%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  </div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:keywords) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <!--<th><%= model_class.human_attribute_name(:owner_id) %></th>-->
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @items.each do |item| %>
        <tr>
          <td><%= link_to item.id, item_path(item) %></td>
          <td><%= item.name %></td>
          <td><%= (sanitize strip_tags(item.description), tags: %w(p)).last((sanitize strip_tags(item.description), tags: %w(p)).length-18).first(200) %></td>
          <td><%= image_tag item.image_url.to_s, size: "100x100" %></td>
          <td><%= number_to_currency(item.price) %></td>
          <td><%= item.keywords %></td>
          <td><%= Category.find(item.category_id).category_name %></td>
          <!--<td><%= item.user_id %></td>-->
          <td><%= time_ago_in_words(item.created_at) %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_item_path(item), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        item_path(item),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
            <%= link_to "renthistory&schedule", items_renthistory_path(item)      %>

          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_item_path,
              :class => 'btn btn-primary' %>

  <%- model_class = Item -%>
  <!--<div class="page-header">
    <h1> All Items </h1>
  </div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th><#%= model_class.human_attribute_name(:id) %></th>
      <th><#%= model_class.human_attribute_name(:name) %></th>
      <th><#%= model_class.human_attribute_name(:description) %></th>
      <th><#%= model_class.human_attribute_name(:image) %></th>
      <th><#%= model_class.human_attribute_name(:price) %></th>
      <th><#%= model_class.human_attribute_name(:keywords) %></th>
      <th><#%= model_class.human_attribute_name(:category_id) %></th>
      <th><#%= model_class.human_attribute_name(:owner_id) %></th>
      <th><#%= model_class.human_attribute_name(:created_at) %></th>
      <th><#%= model_class.human_attribute_name(:availability) %></th>

    </tr>
    </thead>
    <tbody>
    <#% @items1.each do |item| %>
        <tr>
          <td><#%= link_to item.id, item_path(item) %></td>
          <td><#%= item.name %></td>
          <td><#%= (sanitize strip_tags(item.description), tags: %w(p)).last((sanitize strip_tags(item.description), tags: %w(p)).length-18).first(200) %></td>
          <td><#%= image_tag item.image_url.to_s, size: "100x100" %></td>
          <td><#%= number_to_currency(item.price) %></td>
          <td><#%= item.keywords %></td>
          <td><#%= item.category_id %></td>
          <td><#%= item.user_id %></td>
          <td><#%= time_ago_in_words(item.created_at) %></td>
          <td><#%= item.availability %></td>
        </tr>
    <#% end %>
    </tbody>
  </table>-->

</div>

app/views/items/new.html.erb
<div class="container" style="margin-bottom: 15px;">
  <%- model_class = Item -%>
  <div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
  </div>
  <%= render :partial => 'form' %>


</div>

app/views/items/renthistory.html.erb
<div class="container">
  <%- model_class = ItemRequest -%>
  <div class="page-header">
    <h1>Future Schedule</h1>
  </div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:item_id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:fromDate) %></th>
      <th><%= model_class.human_attribute_name(:toDate) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
    </thead>
    <tbody>
    <% @item_requesthistory.each do |item_request| %>
        <tr>
          <td><%= link_to item_request.id, item_request_path(item_request) %></td>
          <td><%= Item.find(item_request.item_id).name %></td>
          <td><%= User.find(item_request.user_id).username %></td>
          <td><%= item_request.fromDate %></td>
          <td><%= item_request.toDate %></td>
          <td><%= item_request.price %></td>
          <td><%= item_request.created_at %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="container">
  <%- model_class = ItemRequest -%>
  <div class="page-header">
    <h1>Past Rent History</h1>
  </div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:item_id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:fromDate) %></th>
      <th><%= model_class.human_attribute_name(:toDate) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
    </thead>
    <tbody>
    <% @item_requestschedule.each do |item_request| %>
        <tr>
          <td><%= link_to item_request.id, item_request_path(item_request) %></td>
          <td><%= Item.find(item_request.item_id).name %></td>
          <td><%= User.find(item_request.user_id).username %></td>
          <td><%= item_request.fromDate %></td>
          <td><%= item_request.toDate %></td>
          <td><%= item_request.price %></td>
          <td><%= item_request.created_at %></td>
        </tr>
    <% end %>
    </tbody>
  </table>


</div>




<%= link_to t('.back', :default => t("helpers.links.back")),
            items_path, :class => 'btn btn-default btn-xs' %>

app/views/items/search.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>


<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 300px;'></div>
</div>

<script type="text/javascript">
    //buildMap(<#%=raw @hash.to_json %>);
    circle1 = [{
        lng: <%= User.find(current_user.id).longitude %>,
        lat: <%= User.find(current_user.id).latitude %>,
        radius: 500
    }];
    circle_options1 = {
        strokeColor: "#29b464",
        strokeOpacity: 0.5,
        strokeWeight: 2,
        fillColor: '#29b464',
        fillOpacity: 0.2
    };
    circle2 = [{
        lng: <%= User.find(current_user.id).longitude %>,
        lat: <%= User.find(current_user.id).latitude %>,
        radius: 2000
    }];
    circle_options2 = {
        strokeColor: "#3b98d4",
        strokeOpacity: 0.5,
        strokeWeight: 2,
        fillColor: '#3b98d4',
        fillOpacity: 0.2
    };
    circle3 = [{
        lng: <%= User.find(current_user.id).longitude %>,
        lat: <%= User.find(current_user.id).latitude %>,
        radius: 3500
    }];
    circle_options3 = {
        strokeColor: "#ffd73c",
        strokeOpacity: 0.5,
        strokeWeight: 2,
        fillColor: '#ffd73c',
        fillOpacity: 0.2
    };
    circle4 = [{
        lng: <%= User.find(current_user.id).longitude %>,
        lat: <%= User.find(current_user.id).latitude %>,
        radius: 5000
    }];
    circle_options4 = {
        strokeColor: "#e64c3c",
        strokeOpacity: 0.5,
        strokeWeight: 2,
        fillColor: '#e64c3c',
        fillOpacity: 0.2
    };
    handler = Gmaps.build('Google');
    handler.buildMap({provider: {minZoom: 11, maxZoom: 19}, internal: {id: 'map'}}, function () {
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        //handler.center.latitude = <#%= User.find(current_user.id).latitude %>;
        //handler.center.longitude = <#%= User.find(current_user.id).longitude %>;
        handler.map.centerOn({
            lat: <%= User.find(current_user.id).latitude %>,
            lng: <%= User.find(current_user.id).longitude %>
        });
        handler.addCircles(circle4, circle_options4);
        handler.addCircles(circle3, circle_options3);
        handler.addCircles(circle2, circle_options2);
        handler.addCircles(circle1, circle_options1);
    });
</script>


<div class="container" style="margin-top: 15px;margin-left: auto; margin-right: auto;padding-left: auto; padding-right: auto;">
  <div class="row" style="margin-left: auto; margin-right: auto; padding-left: auto; padding-right: auto;">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="input-group" style="width: 100%;margin-left: auto; margin-right: auto;padding-left: auto; padding-right: auto;">
        <%= form_tag items_search_path, :method => 'get' do %>
            <div style="width: 80%; float: left;"><%= text_field_tag :search, params[:search], :class => 'form-control', :placeholder => 'Type your item here', :style => 'border-radius: 5px 0 0 5px;' %></div>
            <div style="width: 20%; float: right;"><%= submit_tag 'Search', :name => nil, :class => 'btn btn-default', :style => 'border-radius: 0 5px 5px 0;' %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
    $(document).ready(function (e) {
        $('.search-panel .dropdown-menu').find('a').click(function (e) {
            e.preventDefault();
            var param = $(this).attr("href").replace("#", "");
            var concept = $(this).text();
            $('.search-panel span#search_concept').text(concept);
            $('.input-group #search_param').val(param);
        });
    });
</script>


<div class="container" style="background-color:#ffffff">
  <!--<div class="container container-pad" id="property-listings"><!--style="padding: 30px 15px; padding: 5px!important;">-->

  <div class="row">
    <div class="col-md-12">
      <h1></h1>

      <p></p>
    </div>
  </div>

  <!--div class="row"-->
  <% @item.each do |i| %>
      <div class="" style="padding-left: 0px;">


        <div class="brdr bgc-fff pad-10 box-shad btm-mrg-20 property-listing" style="padding: 5px!important; margin-bottom: 20px!important; background-color: #fff!important; padding: 10px!important; border: 1px solid #ededed; -webkit-box-shadow: 1px 1px 0 rgba(0,0,0,.2);
                box-shadow: 1px 1px 0 rgba(0,0,0,.2);">
          <div class="media" style="padding: 5px!important;">
            <a class="pull-left" href="#" target="_parent" style="padding: 15px;margin: 0; color: #03a1d1;
                    text-decoration: none!important;">
              <!-- <img style="max-width: 180px;" alt="hassan" class="img-responsive" src=""> -->
              <%= image_tag i.image_url.to_s, size: "70x70" %></a>

            <div class="clearfix visible-sm"></div>

            <div class="media-body fnt-smaller" style="padding: 15px; font-size: .9em;">
              <a href="#" target="_parent" style="color: #03a1d1;
                      text-decoration: none!important; margin: 0;"></a>

              <h4 class="media-heading" style="margin: 0px 0px 0px 0px;font-size: x-large;">
                <a href="#" target="_parent" style="margin: 0; color: #03a1d1;
                        text-decoration: none!important;"><%= link_to i.name.first(39), item_path(i) %>
                  <small class="hidden-xs" style="font-size: small; padding: 5px 10px 5px 5px;"><%= i.keywords %></small>
                  <small class="pull-right" style="font-size: medium;padding: 5px 0px 5px 5px;"><%= number_to_currency(i.price) %>
                    <small style="font-size: small;padding: 5px 0px 5px 0px;">/day</small>
                  </small>
                  <br/></a></h4>
              <span class="hidden-xs pull-right fnt-smaller fnt-lighter fnt-arial" style="color: #bbb; font-size: .9em;"><%= i.category.category_name %></span>

              <p class="" style="font-size: medium; margin: 0px; padding: 0px;"><%= (sanitize strip_tags(i.description), tags: %w(p)).last((sanitize strip_tags(i.description), tags: %w(p)).length-18).first(124) %></p>

            </div>
          </div>
        </div>
        <!-- End Listing-->
      </div>
  <% end %>
  <div class="col-sm-6" style="padding-left: 0px; padding-right: 5px; width: 48%;">
    <!--/div-->

    <!--</div>-->
  </div>
</div>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="container-fluid" style="max-width: 1140px; margin: 0 auto;">
  <div class="content-wrapper" style="max-width: 1140px; background: #fff; margin: 0 auto; margin-top: 25px; margin-bottom: 10px; border: 0px; border-radius: 0px;">
    <div class="container" style="padding-left: 0px; padding-right: 0px; max-width: 100%;">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-6" style="float: left; margin: auto;">
            <div class="btn-group cart">
              <%= link_to t('.back', :default => t("helpers.links.back")), items_path, :class => 'btn btn-default' %>
            </div>

          </div>
        </div>
      </div>
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-12" style="float: left;">
            <div class="col-md-6" style="text-align: center; float: left; margin-left: auto; margin-right: auto; margin-top: 25px; margin-bottom: 10px;">
              <span style=""> <%= image_tag @item.image_url.to_s, size: "300x300" %></span>
            </div>
            <div class="col-md-6" style="float: left; margin-left: 0px; margin-right: auto; margin-top: 25px; margin-bottom: 10px;">
              <div class="product-title" style="font-size: 20px;">
                <h1 style="margin-left: 0px;"><%= t '.title', :default => @item.name %>
                  <sub style="font-style: italic; font-size: 15px; color: #F0AD4E;"><%= @item.keywords %></sub></h1>
              </div>
              <div class="product-desc" style="font-size: 16px;"> <%= (sanitize strip_tags(@item.description), tags: %w(p)).last((sanitize strip_tags(@item.description), tags: %w(p)).length-18).first(200) %> </div>
              <!--<div class="product-rating"><i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star-o"></i> </div>-->
              <hr>
              <div class="buttom" style="margin: auto; margin-right: 5px;">
                <div class="col-md-5" style="float: left; margin: 2px 2px 2px 2px;">
                  <div class="product-price" style="font-size: 22px;"> <%= number_to_currency(@item.price) %> </div>
                  <!--div class="product-stock" style="color: #449D44; font-size: 20px; margin-top: 10px;"-->
                  <!--%= @item.availability %-->
                    <!--/div-->
                </div>
                <div class="col-md-4" style="float: left; margin: auto;">
                  <% if (@item.user_id != current_user.id) %>
                      <%= link_to 'Request',
                                  items_rentnow_path(:item => @item.id),
                                  #item_requests_rentnow_path(@item),
                                  :class => 'btn btn-primary', :style => 'margin: 2px 2px 2px 2px; width: 85px;' %>
                  <% end %>
                  <!--button type="button" class="btn btn-danger" style="margin: 2px 2px 2px 2px; width: 85px;">
                    Make Offer
                  </button-->
                </div>
                <br><br><br>
              </div>
              <br>
              <hr>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<div class="container-fluid" style="max-width: 1140px; margin: 0 auto;">
  <div class="col-md-12 product-info" style="margin-top: 5px;">
    <ul id="myTab" class="nav nav-tabs nav_tabs">
      <li class="active"><a href="#service-one" data-toggle="tab">DESCRIPTION</a></li>
      <li><a href="#service-three" data-toggle="tab">REVIEWS</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade in active" id="service-one">
        <section class="container product-info" style="margin-top: 20px; margin-right: 10px; margin-left: 10px;   padding-left: 10px; padding-right: 10px; max-width: 98%;">
          <%= @item.description.html_safe %>
        </section>
      </div>
      <div class="tab-pane fade" id="service-three">
        <section class="container product-info" style="margin-top: 20px; margin-right: 10px; margin-left: 10px;   padding-left: 10px; padding-right: 10px; max-width: 98%;">
          <% @results = Review.where(:item_id => @item.id) %>

          <%  @results.each do |r| %>
              <% @user = User.where(:id => r.user_id).first %>
              Posted by <b><%= @user.username  %></b> since <%= time_ago_in_words(r.created_at) %><br />
              <%= r.try(:body)  %><br /><hr />
          <% end %>
       <% if @item.user_id != current_user.id %>
          <h3>Add a Review</h3>
         <p>
           <%= form_tag('/reviews/create') %>
           <%= hidden_field_tag 'item_id', value = @item.id %>
           <%= text_area_tag 'body' %>
           <br />
           <%= submit_tag 'Add' %>
         </p>
        <% end %>

        </section>
      </div>
    </div>
    <hr>
  </div>
</div>












<!--<div class="page-header">
  <h1><#%=t '.title', :default => @item.name %></h1>
</div>
<div class="media-right media-middle"> --> <!--style="float: left; border: 0px;"> -->
<!--  <#%= image_tag @item.image_url.to_s, size: "200x200" %>
</div>

<dl class="dl-horizontal">-->
<!--<dt><strong><#%= model_class.human_attribute_name(:name) %>:</strong></dt>
<dd><#%= @item.name %></dd>-->
<!--  <dt><strong><#%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><#%= @item.description.html_safe %></dd>-->
<!--<dt><strong><#%= model_class.human_attribute_name(:image) %>:</strong></dt>-->
<!--  <dd></dd>
  <dt><strong><#%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><#%= number_to_currency(@item.price) %></dd>
  <dt><strong><#%= model_class.human_attribute_name(:keywords) %>:</strong></dt>
  <dd><#%= @item.keywords %></dd>
  <dt><strong><#%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><#%= @item.category_id %></dd>
  <dt><strong><#%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><#%= @item.user_id %></dd>
  <dt><strong><#%= model_class.human_attribute_name(:availability) %>:</strong></dt>
  <dd><#%= @item.availability %></dd>
</dl>

<#%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn btn-default'  %>

<#%= link_to 'Send an Offer',
            items_path, :class => 'btn btn-success'  %>
<#% if(@item.availability == "Available") %>
    <#%= link_to 'Rent Now',
                items_rentnow_path(:item => @item.id),
               #item_requests_rentnow_path(@item),
               :class => 'btn btn-primary'  %>
<#% end %>-->
<!--%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn btn-default' %--!>
<!--%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %--!>