config/routes.rb
Rails.application.routes.draw do
  resources :item_requests

  get 'dashboard/index'

  get 'spage/welcome'

  get 'spage/about'

  get 'spage/contact'

  get 'spage/legal'

  get 'spage/privacy'

  get 'items/search'

  get 'items/rentnow'

  get 'acceptoffer/:id' => 'item_requests#acceptoffer'
  get 'rejectoffer/:id' => 'item_requests#rejectoffer'
  get 'userofferindex' =>'item_requests#offerindex'
  get 'userrequestindex' => 'item_requests#requestindex'
  get 'pendingrequestindex' => 'item_requests#pendingrequestindex'
  get 'acceptrequestindex' => 'item_requests#acceptrequestindex'
  get 'rejectrequestindex' => 'item_requests#rejectrequestindex'
  get 'pendingofferindex' => 'item_requests#pendingofferindex'
  get 'acceptofferindex' => 'item_requests#acceptofferindex'
  get 'rejectofferindex' => 'item_requests#rejectofferindex'
  get 'items/renthistory' => 'items#renthistory'

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }
  resources :items
  post 'reviews/create'
  root to: 'spage#welcome'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Passit" %></title>
  <%= csrf_meta_tags %>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application",
          "http://2008.kelvinluck.com/assets/jquery/datePicker/v2/demo/styles/datePicker.css",
          "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", :media => "all" %>
  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  <%= javascript_include_tag "application",
  "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js",
  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js",
  "http://2008.kelvinluck.com/assets/jquery/datePicker/v2/demo/scripts/jquery.datePicker.js"%>
</head>



    <body style="padding-top: 50px;">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!--<a class="navbar-brand" href="#">Brand</a>-->
                    <a class="navbar-brand" href="/" style="padding: 5px 5px 5px 5px;"><%= image_tag "pticon.png",:size => "40x40", :alt=> "PassIt", :title=>"PassIt", :class=>"logo" %></a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><%= link_to "About Us", spage_about_path %></li>
                        <!--<li><a href="#">Link</a></li>-->
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <!--<li><a href="#">Link</a></li>-->
                        <% if user_signed_in? %>
                            <li>
                            <%= link_to('Search', items_search_path) %></li>
                            <li>
                                <%  if current_user.avatar_url.present? %>
                                    <%= link_to image_tag(current_user.avatar_url.to_s, :size => "40x40", :title=>"Dashboard"), dashboard_index_path, {:class => 'navbar-brand', :style => 'margin-left: 0px; text-align: center; float: none; padding: 5px 5px 5px 5px;'} %>
                                <% else %>
                                    <%= link_to image_tag("http://i0.wp.com/coverlandia.net/images/default_avatar.jpg", :size => "40x40", :title=>"Dashboard"), dashboard_index_path, {:class => 'navbar-brand', :style => 'margin-left: 0px; text-align: center; float: none; padding: 5px 5px 5px 5px;'} %>
                                <% end %>
                            </li>
                            <!--<span class="glyphicon glyphicon-search"></span>-->
                        <% else %>
                            <% if !current_page?(new_user_registration_path) %>
                                <li style="text-align: center;">
                                    <%= link_to('Sign up', new_user_registration_path) %>
                                </li>
                            <% end %>
                        <% end %>

                        <% if user_signed_in? %>
                            <li>
                                <%= link_to('Sign out', destroy_user_session_path, :method => :delete) %>
                            </li>
                        <% else %>
                            <% if !current_page?(new_user_session_path) %>
                                <li>
                                    <%= link_to('Sign in', new_user_session_path) %>
                                </li>
                            <% end %>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="panel panel-default" style="border: none; box-shadow: none; margin-bottom: 0px;">
            <div class="container-fluid" style="padding: 0px 0px 0px 0px;">
                <%= bootstrap_flash %>
                <%= yield %>
            </div>
        </div>
        <div class="panel-footer" role="navigation">
            <div class="container">
                <footer>
                    <span>&copy; PassIt 2014</span>  |
                    <span><%= link_to "Contact Us", spage_contact_path %></span>  |
                    <span><%= link_to "Legal", spage_legal_path %></span>  |
                    <span><%= link_to "Privacy Statement", spage_privacy_path %></span>
                </footer>
            </div>
        </div>
    </body>
</html>